#!/usr/bin/env python3
"""
02_train_npe.py

Train Neural Posterior Estimation (NPE/SNPE) with a conditional Neural Spline
Flow (NSF) on landscapes generated by 01_generate_nf_dataset.jl.

The learned object is:
    q_psi(z | F)
where z = log(theta_env).

Commands
--------
Train:
    python 02_train_npe.py train \
        --data nf_results/simulations.csv \
        --prior nf_results/prior_bounds.csv \
        --outdir nf_results/npe \
        --device cuda

Sample a target:
    python 02_train_npe.py sample \
        --model nf_results/npe/posterior.pkl \
        --target nf_results/target_landscape.csv \
        --outdir nf_results/posterior \
        --n-samples 5000

Important
---------
The simulator is deterministic. Exact conditioning on an exact deterministic
landscape can define a very narrow or lower-dimensional inverse set. The
--noise-fraction option adds small synthetic observation/design tolerance to the
fitness vector during NPE training. This makes q(z|F) a distribution over
environments whose landscapes are close to the target, rather than requiring
mathematical equality to machine precision.
"""

from __future__ import annotations

import argparse
import json
import pickle
import random
from pathlib import Path

import numpy as np
import pandas as pd
import torch

try:
    from sbi.inference import SNPE
except ImportError as exc:
    raise ImportError("Install sbi first: pip install sbi") from exc

try:
    from sbi.neural_nets import posterior_nn
except ImportError:
    from sbi.utils.get_nn_models import posterior_nn

try:
    from sbi.utils import BoxUniform
except ImportError:
    from sbi.utils.torchutils import BoxUniform


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_prior(prior_csv: Path):
    prior_df = pd.read_csv(prior_csv)
    required = {"parameter", "z_low", "z_high"}
    if not required.issubset(prior_df.columns):
        raise ValueError(f"{prior_csv} must contain {sorted(required)}")

    names = prior_df["parameter"].astype(str).tolist()
    z_low = torch.tensor(prior_df["z_low"].to_numpy(), dtype=torch.float32)
    z_high = torch.tensor(prior_df["z_high"].to_numpy(), dtype=torch.float32)
    return names, z_low, z_high


def load_dataset(data_csv: Path, names: list[str]):
    df = pd.read_csv(data_csv)

    z_cols = [f"z_{name}" for name in names]
    missing = [c for c in z_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing z columns in dataset: {missing}")

    f_cols = [c for c in df.columns if c.startswith("F_")]
    if not f_cols:
        raise ValueError("No F_* landscape columns found.")

    z = torch.tensor(df[z_cols].to_numpy(), dtype=torch.float32)
    x = torch.tensor(df[f_cols].to_numpy(), dtype=torch.float32)

    if not torch.isfinite(z).all() or not torch.isfinite(x).all():
        raise ValueError("Dataset contains NaN/Inf.")

    return df, z_cols, f_cols, z, x


def load_target(target_csv: Path, expected_k: int) -> torch.Tensor:
    df = pd.read_csv(target_csv)

    if "F_target" in df.columns:
        arr = df["F_target"].to_numpy(dtype=np.float32)
    elif "fitness" in df.columns:
        arr = df["fitness"].to_numpy(dtype=np.float32)
    else:
        numeric = df.select_dtypes(include=[np.number])
        if numeric.shape[1] == 1:
            arr = numeric.iloc[:, 0].to_numpy(dtype=np.float32)
        elif numeric.shape[0] == 1:
            arr = numeric.iloc[0].to_numpy(dtype=np.float32)
        else:
            raise ValueError(
                "Target CSV needs F_target, fitness, one numeric column, or one numeric row."
            )

    arr = np.asarray(arr, dtype=np.float32).reshape(-1)
    if arr.size != expected_k:
        raise ValueError(f"Target has K={arr.size}; model expects K={expected_k}.")
    return torch.from_numpy(arr)


def command_train(args):
    set_seed(args.seed)

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    names, z_low, z_high = load_prior(Path(args.prior))
    raw_df, z_cols, f_cols, z, x = load_dataset(Path(args.data), names)

    n = len(z)
    if n < 100:
        raise ValueError("Too few simulations. Generate at least a few hundred.")

    rng = np.random.default_rng(args.seed)
    indices = rng.permutation(n)
    n_holdout = int(round(args.holdout_fraction * n))
    hold_idx = indices[:n_holdout]
    train_idx = indices[n_holdout:]

    z_train = z[train_idx].clone()
    x_train = x[train_idx].clone()

    raw_df.iloc[hold_idx].to_csv(outdir / "holdout_simulations.csv", index=False)

    # Small synthetic observation/design tolerance for deterministic simulator.
    landscape_scale = x_train.std(dim=0, unbiased=False).clamp_min(1e-8)
    if args.noise_fraction > 0:
        noise = (
            args.noise_fraction
            * landscape_scale[None, :]
            * torch.randn_like(x_train)
        )
        x_train = x_train + noise

    device = args.device
    if device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but torch.cuda.is_available() is False.")

    if device == "cuda":
        torch.set_float32_matmul_precision("high")

    # prior = BoxUniform(low=z_low, high=z_high)
    z_low = z_low.to(device)
    z_high = z_high.to(device)

    prior = BoxUniform(
        low=z_low,
        high=z_high
    )

    density_builder = posterior_nn(
        model="nsf",
        hidden_features=args.hidden_features,
        num_transforms=args.num_transforms,
        z_score_theta="independent",
        z_score_x="independent",
    )

    inference = SNPE(
        prior=prior,
        density_estimator=density_builder,
        device=device,
    )

    inference = inference.append_simulations(z_train, x_train)

    density_estimator = inference.train(
        training_batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        validation_fraction=args.validation_fraction,
        stop_after_epochs=args.stop_after_epochs,
        max_num_epochs=args.max_epochs,
        show_train_summary=True,
    )

    posterior = inference.build_posterior(density_estimator)

    model_path = outdir / "posterior.pkl"
    with model_path.open("wb") as f:
        pickle.dump(posterior, f)

    metadata = {
        "env_parameter_names": names,
        "z_columns": z_cols,
        "fitness_columns": f_cols,
        "n_total": int(n),
        "n_train": int(len(train_idx)),
        "n_holdout": int(len(hold_idx)),
        "seed": int(args.seed),
        "noise_fraction": float(args.noise_fraction),
        "landscape_std_used_for_noise": landscape_scale.tolist(),
        "hidden_features": int(args.hidden_features),
        "num_transforms": int(args.num_transforms),
        "batch_size": int(args.batch_size),
        "learning_rate": float(args.learning_rate),
        "device": device,
        "z_low": z_low.tolist(),
        "z_high": z_high.tolist(),
    }

    with (outdir / "metadata.json").open("w") as f:
        json.dump(metadata, f, indent=2)

    print("\nTRAINING COMPLETE")
    print(f"posterior : {model_path}")
    print(f"metadata  : {outdir / 'metadata.json'}")
    print(f"holdout   : {outdir / 'holdout_simulations.csv'}")


def command_sample(args):
    model_path = Path(args.model)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    metadata_path = model_path.parent / "metadata.json"
    if not metadata_path.exists():
        raise FileNotFoundError(f"Expected metadata beside model: {metadata_path}")

    with metadata_path.open() as f:
        meta = json.load(f)

    names = meta["env_parameter_names"]
    f_cols = meta["fitness_columns"]

    target = load_target(Path(args.target), expected_k=len(f_cols))

    # with model_path.open("rb") as f:
    #     posterior = pickle.load(f)

    # set_seed(args.seed)

    # with torch.no_grad():
    #     z_samples = posterior.sample(
    #         (args.n_samples,),
    #         x=target,
    #         show_progress_bars=True,
    #     ).detach().cpu()

    with model_path.open("rb") as f:
        posterior = pickle.load(f)

    set_seed(args.seed)

    device = "cuda" if torch.cuda.is_available() else "cpu"

    # Move in place — DO NOT assign the result
    posterior.to(device)
    target = target.to(device)

    print("Sampling device:", device)
    print("Target device:", target.device)

    with torch.no_grad():
        z_samples = posterior.sample(
            (args.n_samples,),
            x=target,
            show_progress_bars=True,
        ).detach().cpu()

    theta_samples = torch.exp(z_samples)

    out = {}
    for j, name in enumerate(names):
        out[f"z_{name}"] = z_samples[:, j].numpy()
    for j, name in enumerate(names):
        out[f"theta_{name}"] = theta_samples[:, j].numpy()

    samples_df = pd.DataFrame(out)
    sample_path = outdir / "posterior_samples.csv"
    samples_df.to_csv(sample_path, index=False)

    summary_rows = []
    for j, name in enumerate(names):
        vals = theta_samples[:, j].numpy()
        q = np.quantile(vals, [0.025, 0.25, 0.5, 0.75, 0.975])
        summary_rows.append(
            {
                "parameter": name,
                "mean": float(np.mean(vals)),
                "sd": float(np.std(vals)),
                "q2.5": float(q[0]),
                "q25": float(q[1]),
                "median": float(q[2]),
                "q75": float(q[3]),
                "q97.5": float(q[4]),
            }
        )

    summary_path = outdir / "posterior_summary.csv"
    pd.DataFrame(summary_rows).to_csv(summary_path, index=False)

    target_out = pd.DataFrame(
        {"fitness_column": f_cols, "F_target": target.numpy()}
    )
    target_out.to_csv(outdir / "conditioning_target.csv", index=False)

    print("\nPOSTERIOR SAMPLING COMPLETE")
    print(f"samples : {sample_path}")
    print(f"summary : {summary_path}")
    print("\nNext: validate these theta samples through the original Julia ODE.")


def build_parser():
    parser = argparse.ArgumentParser(
        description="Train/sample NPE with a conditional Neural Spline Flow."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_train = sub.add_parser("train")
    p_train.add_argument("--data", required=True)
    p_train.add_argument("--prior", required=True)
    p_train.add_argument("--outdir", default="nf_results/npe")
    p_train.add_argument(
        "--device",
        choices=["cpu", "cuda"],
        default="cuda" if torch.cuda.is_available() else "cpu",
    )
    p_train.add_argument("--seed", type=int, default=123)
    p_train.add_argument("--holdout-fraction", type=float, default=0.10)
    p_train.add_argument(
        "--noise-fraction",
        type=float,
        default=0.01,
        help=(
            "Gaussian noise SD as a fraction of each landscape feature's "
            "training-set SD. Set 0 for exact deterministic conditioning."
        ),
    )
    p_train.add_argument("--hidden-features", type=int, default=128)
    p_train.add_argument("--num-transforms", type=int, default=5)
    p_train.add_argument("--batch-size", type=int, default=512)
    p_train.add_argument("--learning-rate", type=float, default=5e-4)
    p_train.add_argument("--validation-fraction", type=float, default=0.10)
    p_train.add_argument("--stop-after-epochs", type=int, default=25)
    p_train.add_argument("--max-epochs", type=int, default=300)
    p_train.set_defaults(func=command_train)

    p_sample = sub.add_parser("sample")
    p_sample.add_argument("--model", required=True)
    p_sample.add_argument("--target", required=True)
    p_sample.add_argument("--outdir", default="nf_results/posterior")
    p_sample.add_argument("--n-samples", type=int, default=5000)
    p_sample.add_argument("--seed", type=int, default=321)
    p_sample.set_defaults(func=command_sample)

    return parser


def main():
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
